name: Autofill PR Description

on: pull_request

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04
    steps:
      - uses: hohyon-ryu/openai-pr-description@master
        with:
          max_tokens: 2000
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_model: ${{ vars.OPENAI_API_MODEL }}
          language: "Korean"
